services:
  - type: web
    name: dentalsuite-rental-manager
    env: node
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: dentalsuite-db
          property: connectionString

databases:
  - name: dentalsuite-db
    databaseName: dentalsuite
    user: dentalsuite_user
    plan: free 